version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t api .
      - "docker tag api 184731027435.dkr.ecr.eu-west-2.amazonaws.com/kentnetwork/api:latest"      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - "docker push 184731027435.dkr.ecr.eu-west-2.amazonaws.com/kentnetwork/api:latest"
      - printf '[{"name":"api","imageUri":"184731027435.dkr.ecr.eu-west-2.amazonaws.com/kentnetwork/api:latest"}]' > image.json
artifacts:
  files:
    - 'image.json'
