version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Go code...
      - go build 
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - kent-network-api
